#!/usr/bin/env bash
mvn clean package -Denforcer.skip=true -Dmaven.test.skip=true -Dmdep.skip=true -Dmdep.analyze.skip=true -DignoreNonCompile=true -Dlicense.skip=true -Dair.check.skip-all=true -e -Dair.check.skip-checkstyle=true -Dair.check.skip-license=true
for m in presto-spi presto-base-jdbc presto-raptor presto-wrmsr-mesos presto-wrmsr-yarn ; do
	mvn -pl "$m" install -Denforcer.skip=true -Dmaven.test.skip=true -Dmdep.skip=true -Dmdep.analyze.skip=true -DignoreNonCompile=true -Dlicense.skip=true -Dair.check.skip-all=true -e -Dair.check.skip-checkstyle=true -Dair.check.skip-license=true
done
# java -cp presto-wrmsr-wrapper/target/presto-wrmsr-wrapper-0.109-SNAPSHOT-executable.jar com.wrmsr.presto.wrapper.PrestoWrapperBuilder
